### ISSUE TITLE
Any chance of a patch?

### ISSUE THREAD

**Issue by noxidsoft** [S1SYPHOS/Jekyll-Susy-Starter-Kit#2]
Using Windoze 10, 64bit, etc. Latest Ruby, Gems & Jekyll, etc.

> grunt check
> autoprefixer-core was deprecated. Use autoprefixer package.
> Running "devUpdate:check" (devUpdate) task
> Found 25 devDependencies to check for latest version

Package name    : css-mqpacker
Package type    : devDependencies
Current version : 4.0.1
Wanted version  : 4.0.1
Latest version  : 5.0.1

> > Package is up to date

Package name    : grunt
Package type    : devDependencies
Current version : 0.4.5
Wanted version  : 0.4.5
Latest version  : 1.0.1

> > Package is up to date

Package name    : grunt-cache-bust
Package type    : devDependencies
Current version : 0.6.1
Wanted version  : 0.6.1
Latest version  : 1.3.0

> > Package is up to date

Package name    : grunt-contrib-concat
Package type    : devDependencies
Current version : 0.5.1
Wanted version  : 0.5.1
Latest version  : 1.0.1

> > Package is up to date

Package name    : grunt-contrib-copy
Package type    : devDependencies
Current version : 0.8.2
Wanted version  : 0.8.2
Latest version  : 1.0.0

> > Package is up to date

Package name    : grunt-contrib-cssmin
Package type    : devDependencies
Current version : 0.14.0
Wanted version  : 0.14.0
Latest version  : 1.0.1

> > Package is up to date

Package name    : grunt-contrib-htmlmin
Package type    : devDependencies
Current version : 0.6.0
Wanted version  : 0.6.0
Latest version  : 1.4.0

> > Package is up to date

Package name    : grunt-contrib-jshint
Package type    : devDependencies
Current version : 0.11.3
Wanted version  : 0.11.3
Latest version  : 1.0.0

> > Package is up to date

Package name    : grunt-contrib-uglify
Package type    : devDependencies
Current version : 0.11.1
Wanted version  : 0.11.1
Latest version  : 1.0.1

> > Package is up to date

Package name    : grunt-contrib-watch
Package type    : devDependencies
Current version : 0.6.1
Wanted version  : 0.6.1
Latest version  : 1.0.0

> > Package is up to date

Package name    : grunt-dev-update
Package type    : devDependencies
Current version : 1.4.0
Wanted version  : 1.4.0
Latest version  : 2.0.0

> > Package is up to date

Package name    : grunt-postcss
Package type    : devDependencies
Current version : 0.7.2
Wanted version  : 0.7.2
Latest version  : 0.8.0

> > Package is up to date

Running "jekyll:check" (jekyll) task

> > Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "bundle exec jekyll -v"
> > C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:354:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll (~> 2.5.3) x64-mingw32' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in`each'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in `verify_gemfile_dependencies_are_found!'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:199:in`start'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:183:in `resolve'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:198:in`resolve'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in`specs_for'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in`requested_specs'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:92:in`setup'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
> >      from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in`require'
> >      from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> > Warning: Please install Jekyll before running this task. Use --force to continue.

Aborted due to warnings.

Execution Time (2016-06-14 05:59:03 UTC)
loading tasks     1.8s  █████████████████████████████████ 24%
devUpdate:check   4.6s  █████████████████████████████████████████████████████████████████████████████████████ 64%
jekyll:check     864ms  ████████████████ 12%
Total 7.3s

**Comment by S1SYPHOS** [comment]
I'll look into it, thanks for bringing this to my attention!

**Comment by S1SYPHOS** [comment]
Fixed!

**Comment by noxidsoft** [comment]
Hey thanks, I'll test tomorrow (:

**Comment by S1SYPHOS** [comment]
Glad to help, have a nice day Sir!
